### PR TITLE
Included google analytics

### PR DESCRIPTION
**Pull request by osinakayah**
https://dock-team.atlassian.net/browse/DCK-2133

### CODE REVIEW

**Review by mike-parkhill — COMMENTED** [review]
should we be injecting our keys rather than hard-coding them?

what data does this publish? Have you been able to test it?

**Comment by osinakayah** [comment]
> should we be injecting our keys rather than hard-coding them?
>  The google-services.json file and GoogleService don't contain sensitive information, but on second thought though, we can add them in .gitignore
> what data does this publish? Have you been able to test it?


It publishes data about the number of users we have, their demographic, age, country, where they are accessing it from, the version they have, the phone model etc.

**Comment by mike-parkhill** [comment]
Cool, yep I see it in the new project I created on GA. Looks a bit limited in details, but we can no doubt flesh that out in the future.

**Comment by mike-parkhill** [comment]
what about this question?

> should we be injecting our keys rather than hard-coding them?

**Review by mike-parkhill — APPROVED** [review]
Thanks for moving the credentials out.

**Pull request merged**
