### PR TITLE
Make Credentials as default screen

### PR DESCRIPTION
**Pull request by Jayteekay**
## Proposed Changes
- Rearranging the bottom navigation tabs in the order Credials, DIDs, QR Scanner, Tokens, and Settings
- Setting "Credentials" as the default screen when user is authenticated

## Testing instructions
- Before and after configurations of the bottom navigation can be seen below:
Screenshot 2023-04-04 at 10 36 58 AM -> Screenshot 2023-04-04 at 10 36 00 AM
- On login into the wallet app, the first screen shown should be the Credentials screen.

### CODE REVIEW

**Review by maycon-mello — APPROVED** [review]
looks good

**Review by mike-parkhill — COMMENTED** [review]
Looks good, but wondering if it would make more sense to have Creds and DIDs to the left of the Scanner option and Tokens and Settings to the right. 

Feels like better logical grouping to me, but it's not a strongly held opinion.

**Comment by maycon-mello** [comment]
> Looks good, but wondering if it would make more sense to have Creds and DIDs to the left of the Scanner option and Tokens and Settings to the right.
> 
> Feels like better logical grouping to me, but it's not a strongly held opinion.

good point, I agree. Creds, DIDs, QR Scanner, Tokens, and Settings looks a logical grouping

**Comment by SamHellawell** [comment]
+1 on moving tokens to the right

**Comment by Jayteekay** [comment]
> Looks good, but wondering if it would make more sense to have Creds and DIDs to the left of the Scanner option and Tokens and Settings to the right.
> 
> Feels like better logical grouping to me, but it's not a strongly held opinion.

Agreed. That change has been included now.

**Review by mike-parkhill — COMMENTED** [review]
We don't have any snapshots that capture this?

**Comment by Jayteekay** [comment]
> We don't have any snapshots that capture this?

**Review by maycon-mello — APPROVED** [review]

**Pull request merged**
